import Head from 'next/head'
import Image from 'next/image'
import {ViewGridIcon,MicrophoneIcon,SearchIcon} from "@heroicons/react/solid"
import {useRef,useState} from "react"
import {useRouter} from "next/router"

export default function Home() {
  const router = useRouter()
  const searchInputRef = useRef(null);
  const [input, setInput]=useState(null)

  const search = event =>{
    event.preventDefault();
    const term = searchInputRef.current.value
    console.log(term)
    router.push(`/search?term=${term} `);
   
  }
  return (
    <div >
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <header className="flex justify-between w-full mt-5 text-sm text-gray-700">
        <div className=" flex space-x-4 items-center">
          
        </div>

        <div className=" flex space-x-4 items-center ">
          <p className="hover:underline cursor-pointer ">Gmail</p>
          <p className="hover:underline cursor-pointer ">Images</p>
          <ViewGridIcon className="w-10 h-10 text-gray-700 p-2 cursor-pointer hover:scale-110 hover:bg-gray-300 rounded-full"/>
          <Image
            src="/userlogo.png"
            loading="lazy"  
            alt="profilepic" 
            width={40}
            height={40}
            className="rounded-full  cursor-pointer duration-150 transform hover:scale-110"
          />
        </div>

      </header>
      {/* Main */}
      <form className="flex flex-grow mt-32  items-center text-center flex-col">  
        <Image
            src="/2.gif"
            loading="lazy"  
            alt="profilepic" 
            width={400}
            height={160}
            className="rounded-full   duration-150 transform hover:scale-110"
          />

        <div className="flex rouned-xl w-full space-x-2 p-5 rounded-full  items-center mt-5 lg:max-w-2xl max-w-md border border-gray-200 px-5 py-3 shadow-md  sm:max-w-xl">
          <SearchIcon className="h-5 mr-3  text-gray-500 flex "/>
          <input type="text" ref={searchInputRef}    placeholder="Введите поисковый запрос или URL" className="felx focus:outline-none w-full"/>
          <MicrophoneIcon className="h-5 mr-3 text-blue-700 flex cursor-pointer "/>
          <button hidden type="submit" className=' ' onClick={search}/>
        </div>
        <div className='flex  items-center mt-5  space-x-2 '>
          <button onClick={search} className='text-sm  p-3 rounded-md ring-gray-200 bg-gray-100 text-gray-800 hover:ring-1 focus:outline-none active:ring-gray-300 hover:shadow-md'>Google поиск</button>
          <button className='text-sm invisible sm:visible   p-3 rounded-md ring-gray-200 bg-gray-100 text-gray-800 hover:ring-1 focus:outline-none active:ring-gray-300  hover:shadow-md '>Тебе повезет</button>
        </div>



        <div className='flex flex-col mt-5'> 
          <div className='   items-center grid sm:grid-cols-5  grid-cols-3  '>
            <div className='flex flex-col items-center p-6  cursor-pointer hover:bg-gray-200 rounded-lg'>
              <Image
                src="/5.png"
                loading="lazy"  
                alt="profilepic" 
                width={40} height={40}
                clasName="flex rounded-full bg-gray-100"
              />
              <p className='text-sm mt-3 flex'>Youtube</p>
            </div>
            <div className='flex flex-col items-center p-6  cursor-pointer hover:bg-gray-200 rounded-lg'>
            <Image
                src="/fblogo.png"
                loading="lazy"  
                alt="profilepic" 
                width={40} height={40}
                clasName="flex rounded-full bg-gray-100"
              />
              <p className='text-sm mt-3 flex'>Facebook</p>
            </div>
            <div className='flex flex-col items-center p-6  cursor-pointer hover:bg-gray-200 rounded-lg'>
              <Image
                src="/logo.png"
                loading="lazy"  
                alt="profilepic" 
                width={40} height={40}
                clasName="flex rounded-full bg-gray-100"
              />
              <p className='text-sm mt-3 flex'>Manager.com</p>
            </div>
            <div className='flex flex-col items-center p-6  cursor-pointer hover:bg-gray-200 rounded-lg'>
              <Image
                src="/6.jpeg"
                loading="lazy"  
                alt="profilepic" 
                width={40} height={40}
                clasName="flex rounded-full bg-gray-100"
              />
              <p className='text-sm mt-3 flex'>Spotify</p>
            </div>
            <div className='flex flex-col items-center p-6  cursor-pointer hover:bg-gray-200 rounded-lg'>
            <Image
                src="/7.png"
                loading="lazy"  
                alt="profilepic" 
                width={40} height={40}
                clasName="flex rounded-full bg-gray-100"
              />
              <p className='text-sm mt-3 flex'>Vercel</p>
            </div>
          
            <div className='flex flex-col items-center p-6  cursor-pointer hover:bg-gray-200 rounded-lg'>
            <Image
                src="/7.png"
                loading="lazy"  
                alt="profilepic" 
                width={40} height={40}
                clasName="flex rounded-full bg-gray-100"
              />

              <p className='text-sm mt-3 flex'>Vercel</p>
            </div>
            <div className='flex flex-col items-center p-6  cursor-pointer hover:bg-gray-200 rounded-lg'>
              <Image
                src="/5.png"
                loading="lazy"  
                alt="profilepic" 
                width={40} height={40}
                clasName="flex rounded-full bg-gray-100"
              />
              <p className='text-sm mt-3 flex'>Youtube</p>
            </div>
            <div className='flex flex-col items-center p-6  cursor-pointer hover:bg-gray-200 rounded-lg'>
              <Image
                src="/fblogo.png"
                loading="lazy"  
                alt="profilepic" 
                width={40} height={40}
                clasName="flex rounded-full bg-gray-100"
              />
              <p className='text-sm mt-3 flex'>Facebook</p>
            </div>
            <div className='flex flex-col items-center p-6  cursor-pointer hover:bg-gray-200 rounded-lg'>
              <Image
                src="/7.png"
                loading="lazy"  
                alt="profilepic" 
                width={40} height={40}
                clasName="flex rounded-full bg-gray-100"
              />
              <p className='text-sm mt-3 flex'>Vercel</p>
            </div>
            
          </div>
        </div>

      </form>
      {/* Footer */}
    </div>
  )
}
