import React from 'react'
import Head from 'next/head'

import Header from "../components/Header"
import Response from "../Response"
import { useRouter } from 'next/router'

import SearchResult from "../components/SearchResult"


function Search({results}) {
    const router = useRouter(null);
   console.log(results)
  return (
    <div>
        <Head>
        <title>{router.query.term} - google search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* Header */}
        <Header/>
        {/* Search Result */}
        <SearchResult results={results}/>
        
    </div>
  )
}

export async function getServerSideProps(context){
    const useData = false;
    const startIndex = context.query.start || '0';
    const data = useData ? Response :   await fetch(`https://www.googleapis.com/customsearch/v1?key=${process.env.API_KEY}&cx=${process.env.CONTEXT_KEY}&q=${context.query.term}&start=${startIndex}`
    ).then(response =>response.json());

    return {
        props: {
            results: data,
        }
    }


}

export default Search